### ISSUE TITLE
 Installation problem (roundcube 1.4.9)

### ISSUE THREAD

**Issue by effectsno1** [pulsejet/roundcube-oidc#4]
php 7.3.23
roundcube 1.4.9

I am trying to connect with keycloak.

I don't know what's the problem.

I have a very low level of program knowledge.

-------------------------------------------------------------------

  Problem 1
    - endroid/qr-code is locked to version 1.6.6 and an update of this package was not requested.
    - endroid/qr-code 1.6.6 requires ext-gd * -> it is missing from your system. Install or enable PHP's gd extension.
  Problem 2
    - pear/net_ldap2 v2.2.0 requires ext-ldap * -> it is missing from your system. Install or enable PHP's ldap extension.
    - kolab/net_ldap3 v1.1.3 requires pear/net_ldap2 >=2.0.12 -> satisfiable by pear/net_ldap2[v2.2.0].
    - kolab/net_ldap3 is locked to version v1.1.3 and an update of this package was not requested.

To enable extensions, verify that they are enabled in your .ini files:
    -
    - /usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-pdo_pgsql.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-zip.ini
    - /usr/local/etc/php/conf.d/roundcube.ini
    - /usr/local/etc/php/conf.d/timezone.ini
You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

---------------------------------------------------------------------------------------------

**Comment by pulsejet** [comment]
This has nothing to do with this plugin. You probably need to install the `php-gd` and `php-ldap` extensions
