### ISSUE TITLE
Auto create IMAP user on SSO login

### ISSUE THREAD

**Issue by DaveLomber** [pulsejet/roundcube-oidc#5]
Hi there

Is there ant way to auto create IMAP user on 1st SSO login? 

When use SSO login - this is what's expected: a user just uses own creds and login to the service.

Did not find anything about it in docs/configs

Please clarify

**Comment by pulsejet** [comment]
Out of scope for this plugin.

You will have to create an external hook to call when the user doesn't exist, but this will probably be very complicated.
